# Generated by Django 5.1.6 on 2025-02-12 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
